apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: scanner-master
spec:
  template:
    metadata:
      labels:
        app: scanner
    spec:
      containers:
        - name: master
          image: wcrichto/scanner-kube:master
          imagePullPolicy: Always
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /secret/google-key.json
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-storage-key
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-storage-key
                  key: AWS_SECRET_ACCESS_KEY
          volumeMounts:
            - name: google-key
              mountPath: /secret
      volumes:
        - name: google-key
          secret:
            secretName: google-key
            items:
              - key: google-key.json
                path: google-key.json
