version: '2'

services:
  scanner-client:
    build:
      context: .
      dockerfile: docker/Dockerfile-local
    command: ["sleep", "infinity"]
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - .:/app
      - ~/.bash_history:/root/.bash_history
      - .scanner.toml:/root/.scanner.toml
    ports:
      - "8001:8001"
