version: '2'

services:
  scanner-client:
    build:
      context: .
      dockerfile: docker/Dockerfile-local
      args:
        project: visualdb-1046
        zone: us-east1-d
    command: ["python", "cluster.py", "serve"]
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - .:/app
      - ~/.bash_history:/root/.bash_history
      - .scanner.toml:/root/.scanner.toml
    ports:
      - "8001:8001"
