FROM scannerresearch/scanner:cpu
ARG project
ARG zone

# Install Ubuntu packages
RUN apt-get update && apt-get install -y curl emacs
RUN export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)" && \
    echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && \
    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - && \
    apt-get update && apt-get install -y google-cloud-sdk kubectl

# TODO(wcrichto): is there a way to mount .:/app during build to avoid the ADDs here?
WORKDIR /app

ADD docker/requirements-local.txt google-key.json cluster.py cluster_utils.py .scanner.toml ./
RUN pip install -r requirements-local.txt
RUN python cluster.py auth
ENV GOOGLE_APPLICATION_CREDENTIALS=/app/google-key.json
