FROM scannerresearch/scanner:worker

ADD .scanner.toml /root/.scanner.toml
ADD docker/requirements-cluster.txt .
RUN pip install -r requirements-cluster.txt

RUN git clone https://github.com/tensorflow/models && \
    wget http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_coco_11_06_2017.tar.gz && \
    tar -xf ssd_mobilenet_v1_coco_11_06_2017.tar.gz && \
    cd models && \
    protoc object_detection/protos/*.proto --python_out=.

ENV PYTHONPATH /app/models/slim:/app/models:/app/models/object_detection:$PYTHONPATH
